library(rmarkdown)
render_site("classic-vs-bayes.Rmd")
render_site("ERC-example.Rmd")
render_site("ERC-example-prior.Rmd")
render_site("ERC-example-cv.Rmd")
render_site("mcmc.Rmd")
render_site("links.Rmd")
render_site("index.Rmd")
# render_site()
