---
title: "A Primer on Bayesian Inference for Accounting Research"
description: |
  Welcome to the companion website for the paper *What Can Bayesian Inference Do for Accounting Research?* I hope this site and the accompanying [GitHub repo](https://github.com/hschuett/BayesForAccountingResearch) will help those interested in Bayesian methods to find a starting point. Hopefully you find it useful.
author:
  - name: Harm Schuett
    url: https://hschuett.github.io/
    affiliation: Tilburg University
    affiliation_url: https://www.tilburguniversity.edu
date: "`r Sys.Date()`"
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

The site is organized as follows. The first part provides the annotated code to produce the output and figures used in the paper (the [GitHub repo](https://github.com/hschuett/BayesForAccountingResearch) also contains the code to compute the data used). Code can be copied easily to the clipboard and be reused. The second part is still under development and contains additional material useful to those interested in Bayesian analysis.

## Paper code

- [Section 2: Simulation](classic-vs-bayes.html) contains all the code to replicate the figures and results from Section 2, which compares Classical hypothesis testing to Bayesian inference.

- [Section 3: ERC Example](ERC-example.html) contains all the code to replicate the figures and results from the ERC example in Section 3. Only the prior predictive checks and cross-validation test are kept in the separate files (below).

- [Section 3: ERC Prior Check](ERC-example-prior.html) contains the code to replicate the prior simulation check from the ERC example in Section 3.

- [Section 3: ERC Crossval Test](ERC-example-cv.html) contains the code to replicate the 10-fold cross validation test from the ERC example in Section 3.

## Additional material

- [MCMC primer](mcmc.html) is a very very brief explanation of how Bayesian models are fit using MCMC techniques. Definitely check out the links here that point towards more in-depth explanations.

- [Useful Links](links.html) is a collection of links to documentation, tutorials, videos, and other helpful material for those interested in learning about Bayesian statistics.
